#!/bin/bash
echo "WebJ Script Starts " 

mkdir target/tomcat.$PORT
mkdir target/tomcat.$PORT/webapps

cp utils/webjdata.ini target/tomcat.$PORT/webapps/

curl -o utils/WebJ.war  https://raw.githubusercontent.com/webjframework/webj/master/WebJ.war  

java  -Xmx300m -Xss512k -Dfile.encoding=UTF-8  -jar utils/webapp-runner.jar --port $PORT --expanded-dir-name WEBJ --expand-war utils/WebJ.war

